### ISSUE TITLE
The installation procedure in the README doesn't work

### ISSUE THREAD

**Issue by kmedidi** [openshift/whereabouts-cni#45]
After cloning, the command to install is mentioned as follows

`kubectl apply -f ./doc/daemonset-install.yaml -f ./doc/whereabouts.cni.cncf.io_ippools.yaml -f ./doc/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml`

But there is no file named `doc/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml` in the cloned directory.

**Comment by dougbtv** [comment]
Hey @kmedidi -- thanks for the heads up. I think the issue here is that you probably want to use the upstream community distribution: https://github.com/dougbtv/whereabouts -- this particular GitHub repository is for shipping Whereabouts with OpenShift. 

...I'm going to update the README here to make sure people are in the right place. Thanks for letting me know, I appreciate it
